
-- =============================================================
--  مغسلتي اس بلس — Maghsalati S Plus
--  PostgreSQL Database Schema v4.0
--  قاعدة بيانات كاملة مع Enums و Indexes و Constraints
-- =============================================================
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ads
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    media_urls jsonb NOT NULL,
    body_text text COLLATE pg_catalog."default",
    link_url text COLLATE pg_catalog."default",
    target_audience ad_target NOT NULL DEFAULT 'all'::ad_target,
    sort_order integer DEFAULT 0,
    start_date date,
    end_date date,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app_settings
(
    key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    updated_by uuid,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    laundry_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    booking_date date NOT NULL,
    booking_time time without time zone NOT NULL,
    notes text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    invoice_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT bookings_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.bookings
    IS 'حجوزات المواعيد المسبقة — يُربط بفاتورة عند التنفيذ';

CREATE TABLE IF NOT EXISTS public.categories
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    laundry_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_laundry_id_name_key UNIQUE (laundry_id, name)
);

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    laundry_id uuid,
    customer_id uuid,
    admin_id uuid,
    sender_id uuid NOT NULL,
    message text COLLATE pg_catalog."default",
    attachment_url text COLLATE pg_catalog."default",
    attachment_type character varying(20) COLLATE pg_catalog."default",
    is_read boolean NOT NULL DEFAULT false,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.chat_messages
    IS 'محادثات: عميل↔مغسلة | عميل↔إدارة | مغسلة↔إدارة';

CREATE TABLE IF NOT EXISTS public.invoice_items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    invoice_id uuid NOT NULL,
    item_id uuid,
    item_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    unit_price numeric(8, 2) NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    subtotal numeric(10, 2) GENERATED ALWAYS AS ((unit_price * (quantity)::numeric)) STORED,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    item_name_ar character varying(150) COLLATE pg_catalog."default",
    item_name_en character varying(150) COLLATE pg_catalog."default",
    service_type service_type NOT NULL DEFAULT 'washing_and_ironing'::service_type,
    processing_type processing_type NOT NULL DEFAULT 'normal'::processing_type,
    CONSTRAINT invoice_items_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.invoice_items.item_name
    IS 'مخزّن كنص ثابت حتى لو تغيّر اسم الصنف لاحقاً';

COMMENT ON COLUMN public.invoice_items.unit_price
    IS 'مخزّن كقيمة ثابتة حتى لو تغيّر السعر لاحقاً';

COMMENT ON COLUMN public.invoice_items.service_type
    IS 'نوع الخدمة: غسيل / كوي / غسيل+كوي';

COMMENT ON COLUMN public.invoice_items.processing_type
    IS 'عادي أو مستعجل';

CREATE TABLE IF NOT EXISTS public.invoice_status_log
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    invoice_id uuid NOT NULL,
    changed_by uuid NOT NULL,
    old_status invoice_status,
    new_status invoice_status NOT NULL,
    note text COLLATE pg_catalog."default",
    changed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT invoice_status_log_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.invoice_status_log
    IS 'سجل تدقيقي كامل لكل تغيير في حالة الفاتورة';

CREATE TABLE IF NOT EXISTS public.invoices
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    invoice_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    laundry_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    status invoice_status NOT NULL DEFAULT 'received'::invoice_status,
    payment_type payment_type NOT NULL DEFAULT 'cash'::payment_type,
    subtotal numeric(10, 2) NOT NULL DEFAULT 0.00,
    discount numeric(10, 2) NOT NULL DEFAULT 0.00,
    total_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    paid_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    due_amount numeric(10, 2) GENERATED ALWAYS AS ((total_amount - paid_amount)) STORED,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    walk_in_name character varying(150) COLLATE pg_catalog."default",
    walk_in_phone character varying(20) COLLATE pg_catalog."default",
    walk_in_location text COLLATE pg_catalog."default",
    expected_delivery_at timestamp with time zone,
    tax_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    urgency_fee numeric(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT invoices_invoice_number_key UNIQUE (invoice_number)
);

COMMENT ON COLUMN public.invoices.invoice_number
    IS 'رقم تسلسلي مُنسق: LAU-{YYYY}-{000000}';

COMMENT ON COLUMN public.invoices.due_amount
    IS 'عمود محسوب تلقائياً: total - paid (للآجل)';

COMMENT ON COLUMN public.invoices.walk_in_name
    IS 'اسم العميل غير المسجل في التطبيق';

COMMENT ON COLUMN public.invoices.walk_in_phone
    IS 'رقم هاتف العميل غير المسجل';

COMMENT ON COLUMN public.invoices.expected_delivery_at
    IS 'تاريخ ووقت التسليم المتوقع';

CREATE TABLE IF NOT EXISTS public.items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    category_id uuid NOT NULL,
    name_ar character varying(150) COLLATE pg_catalog."default" NOT NULL,
    name_en character varying(150) COLLATE pg_catalog."default" NOT NULL,
    base_price numeric(8, 2) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    washing_price numeric(8, 2),
    ironing_price numeric(8, 2),
    CONSTRAINT items_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.items.base_price
    IS 'سعر الغسيل + الكوي معاً (الخدمة الكاملة)';

COMMENT ON COLUMN public.items.washing_price
    IS 'سعر الغسيل فقط — مختلف عن سعر الكوي';

COMMENT ON COLUMN public.items.ironing_price
    IS 'سعر الكوي فقط — مختلف عن سعر الغسيل';

CREATE TABLE IF NOT EXISTS public.laundries
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    owner_id uuid NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    country character varying(10) COLLATE pg_catalog."default" DEFAULT 'SA'::character varying,
    latitude numeric(10, 8),
    longitude numeric(11, 8),
    working_hours jsonb,
    logo_url text COLLATE pg_catalog."default",
    status laundry_status NOT NULL DEFAULT 'pending'::laundry_status,
    rating_avg numeric(3, 2) DEFAULT 0.00,
    rating_count integer DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    tax_enabled boolean NOT NULL DEFAULT false,
    tax_rate numeric(5, 2) DEFAULT 0.00,
    urgency_enabled boolean NOT NULL DEFAULT false,
    urgency_fee numeric(8, 2) DEFAULT 0.00,
    CONSTRAINT laundries_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.laundries.working_hours
    IS 'مثال: {"sun":{"open":"08:00","close":"22:00","closed":false}}';

COMMENT ON COLUMN public.laundries.rating_avg
    IS 'يُحدَّث تلقائياً عبر trigger عند إضافة تقييم جديد';

COMMENT ON COLUMN public.laundries.tax_rate
    IS 'نسبة الضريبة بالمئة — قابلة للتعديل';

COMMENT ON COLUMN public.laundries.urgency_fee
    IS 'رسوم الاستعجال بالقيمة الثابتة — قابلة للتعديل';

CREATE TABLE IF NOT EXISTS public.laundry_prices
(
    laundry_id uuid NOT NULL,
    item_id uuid NOT NULL,
    price numeric(8, 2) NOT NULL,
    is_available boolean NOT NULL DEFAULT true,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT laundry_prices_pkey PRIMARY KEY (laundry_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default",
    reference_id uuid,
    is_read boolean NOT NULL DEFAULT false,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.promo_codes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    discount_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(10, 2) NOT NULL,
    max_uses integer,
    used_count integer NOT NULL DEFAULT 0,
    valid_from date,
    valid_until date,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
    CONSTRAINT promo_codes_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.promotion_views
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    promotion_id uuid,
    ad_id uuid,
    user_id uuid,
    viewed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT promotion_views_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.promotions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    laundry_id uuid NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT promotions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    invoice_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    laundry_id uuid NOT NULL,
    stars smallint NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ratings_pkey PRIMARY KEY (id),
    CONSTRAINT ratings_invoice_id_customer_id_key UNIQUE (invoice_id, customer_id),
    CONSTRAINT ratings_invoice_id_key UNIQUE (invoice_id)
);

COMMENT ON COLUMN public.ratings.invoice_id
    IS 'UNIQUE يضمن تقييماً واحداً فقط لكل فاتورة';

CREATE TABLE IF NOT EXISTS public.subscription_plans
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name_ar character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name_en character varying(100) COLLATE pg_catalog."default" NOT NULL,
    duration_days integer NOT NULL,
    price_sar numeric(10, 2) NOT NULL,
    features jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_seasonal boolean NOT NULL DEFAULT false,
    occasion_name character varying(100) COLLATE pg_catalog."default",
    discount_percent numeric(5, 2) DEFAULT 0.00,
    offer_valid_from date,
    offer_valid_until date,
    CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.subscription_plans.is_seasonal
    IS 'هل هذه خطة موسمية (عيد / رمضان...)';

COMMENT ON COLUMN public.subscription_plans.occasion_name
    IS 'اسم المناسبة مثل: العيد الوطني';

COMMENT ON COLUMN public.subscription_plans.discount_percent
    IS 'نسبة الخصم الموسمي';

CREATE TABLE IF NOT EXISTS public.subscriptions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    laundry_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    amount_paid numeric(10, 2) NOT NULL DEFAULT 0.00,
    payment_method character varying(50) COLLATE pg_catalog."default" DEFAULT 'manual'::character varying,
    promo_code character varying(50) COLLATE pg_catalog."default",
    start_date date NOT NULL DEFAULT CURRENT_DATE,
    end_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    notes text COLLATE pg_catalog."default",
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.subscriptions
    IS 'يمكن أن يكون لكل مغسلة أكثر من سجل (تاريخ اشتراكات)';

CREATE TABLE IF NOT EXISTS public.support_tickets
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    user_type ticket_user_type NOT NULL,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    admin_reply text COLLATE pg_catalog."default",
    status ticket_status NOT NULL DEFAULT 'open'::ticket_status,
    resolved_by uuid,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT support_tickets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_devices
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    device_type character varying(50) COLLATE pg_catalog."default",
    device_os character varying(50) COLLATE pg_catalog."default",
    device_model character varying(100) COLLATE pg_catalog."default",
    fcm_token text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT false,
    is_primary boolean NOT NULL DEFAULT false,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    device_name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT user_devices_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.user_devices.device_name
    IS 'اسم مخصص من المستخدم مثل: آيفون الشغل';

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default",
    unique_id character varying(12) COLLATE pg_catalog."default" NOT NULL,
    qr_code text COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default",
    role user_role NOT NULL DEFAULT 'customer'::user_role,
    is_active boolean NOT NULL DEFAULT true,
    is_verified boolean NOT NULL DEFAULT false,
    last_login_at timestamp with time zone,
    device_token text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    email character varying(255) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default",
    country character varying(10) COLLATE pg_catalog."default" DEFAULT 'SA'::character varying,
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'SAR'::character varying,
    google_id character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_google_id_key UNIQUE (google_id),
    CONSTRAINT users_phone_number_key UNIQUE (phone_number),
    CONSTRAINT users_unique_id_key UNIQUE (unique_id)
);

COMMENT ON TABLE public.users
    IS 'جميع مستخدمي النظام: عملاء، أصحاب مغاسل، مدراء';

COMMENT ON COLUMN public.users.unique_id
    IS 'معرف فريد قصير يُستخدم لإنشاء فاتورة أو مسح QR';

COMMENT ON COLUMN public.users.device_token
    IS 'رمز جهاز Firebase لإرسال الإشعارات الفورية';

COMMENT ON COLUMN public.users.google_id
    IS 'معرف حساب Google للمستخدمين المسجلين عبر Google OAuth';

ALTER TABLE IF EXISTS public.ads
    ADD CONSTRAINT ads_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.app_settings
    ADD CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bookings_customer
    ON public.bookings(customer_id);


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.invoice_items
    ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice
    ON public.invoice_items(invoice_id);


ALTER TABLE IF EXISTS public.invoice_items
    ADD CONSTRAINT invoice_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.invoice_status_log
    ADD CONSTRAINT invoice_status_log_changed_by_fkey FOREIGN KEY (changed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoice_status_log
    ADD CONSTRAINT invoice_status_log_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.items
    ADD CONSTRAINT items_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_items_category
    ON public.items(category_id);


ALTER TABLE IF EXISTS public.laundries
    ADD CONSTRAINT laundries_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_laundries_owner
    ON public.laundries(owner_id);


ALTER TABLE IF EXISTS public.laundry_prices
    ADD CONSTRAINT laundry_prices_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.laundry_prices
    ADD CONSTRAINT laundry_prices_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notif_unread
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.promo_codes
    ADD CONSTRAINT promo_codes_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.promotion_views
    ADD CONSTRAINT promotion_views_ad_id_fkey FOREIGN KEY (ad_id)
    REFERENCES public.ads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ad_views
    ON public.promotion_views(ad_id);


ALTER TABLE IF EXISTS public.promotion_views
    ADD CONSTRAINT promotion_views_promotion_id_fkey FOREIGN KEY (promotion_id)
    REFERENCES public.promotions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_promo_views
    ON public.promotion_views(promotion_id);


ALTER TABLE IF EXISTS public.promotion_views
    ADD CONSTRAINT promotion_views_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.promotions
    ADD CONSTRAINT promotions_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT ratings_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_customer
    ON public.ratings(customer_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT ratings_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ratings_invoice_id_key
    ON public.ratings(invoice_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT ratings_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_laundry_id_fkey FOREIGN KEY (laundry_id)
    REFERENCES public.laundries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_subscriptions_laundry
    ON public.subscriptions(laundry_id);


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.subscription_plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.support_tickets
    ADD CONSTRAINT support_tickets_resolved_by_fkey FOREIGN KEY (resolved_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.support_tickets
    ADD CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tickets_user
    ON public.support_tickets(user_id);


ALTER TABLE IF EXISTS public.user_devices
    ADD CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_devices_primary
    ON public.user_devices(user_id);

END;